version: '{build}'
max_jobs: 1

branches:
  only:
    - master

image: Visual Studio 2019 Preview
configuration: Release

install:
  - dotnet tool install -g coveralls.net --version 1.0.0

before_build:
  - nuget restore -verbosity quiet

build:
  project: SharpCollections.sln
  verbosity: minimal

test_script:
  - dotnet test ./test/SharpCollections.Tests -c Release --no-build && dotnet test ./test/SharpCollections.Tests -c Debug && dotnet test ./test/SharpCollections.Tests -c Release -f netcoreapp3.0 /p:CollectCoverage=true /p:Include=\"[SharpCollections*]*\" /p:CoverletOutputFormat=opencover /p:CoverletOutput=../../coverage.xml
 
after_test:
  - csmacnz.Coveralls --opencover -i ./coverage.xml --useRelativePaths