dist: trusty
sudo: false

language: csharp
mono: none
dotnet: 2.1.403

script: >
  dotnet build -c Release &&
  dotnet test test/SharpCollections.Tests -c Release --no-build --list-tests &&
  dotnet test test/SharpCollections.Tests -c Release --no-build

notifications:
  email: false