dist: xenial
sudo: false

language: csharp
mono: none
dotnet: 3.0.100

script: >
  dotnet build -f netcoreapp2.1 -c Release &&
  dotnet build -f netcoreapp2.1 -c Debug &&
  dotnet test test/SharpCollections.Tests -f netcoreapp2.1 -c Release --no-build --list-tests &&
  dotnet test test/SharpCollections.Tests -f netcoreapp2.1 -c Release --no-build &&
  dotnet test test/SharpCollections.Tests -f netcoreapp2.1 -c Debug --no-build

notifications:
  email: false