dist: xenial
sudo: required

language: csharp
mono: none
dotnet: 2.2.300

addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: latest/beta

script: >
  sudo snap alias dotnet-sdk.dotnet dotnet &&
  dotnet --version &&
  dotnet build -f netcoreapp3.0 -c Release &&
  dotnet build -f netcoreapp3.0 -c Debug &&
  dotnet test test/SharpCollections.Tests -f netcoreapp3.0 -c Release --no-build --list-tests &&
  dotnet test test/SharpCollections.Tests -f netcoreapp3.0 -c Release --no-build &&
  dotnet test test/SharpCollections.Tests -f netcoreapp3.0 -c Debug --no-build

notifications:
  email: false